### ISSUE TITLE
How to use these plugins? 

### ISSUE THREAD

**Issue by jainrocks** [Kong/go-plugins#10]
How to use these plugins? Any example or the guide will be of great help.
I followed below steps:

1. added `go_plugins_dir = /usr/local/kong/goplugins` inside the kong.conf file
2. created the folder at `/usr/local/kong/goplugins` and added `go-hello.go` from https://github.com/Kong/go-plugins
3. Tried finding the same through `curl localhost:8001` but can not find go-hello

output of above curl
`{"plugins":{"enabled_in_cluster":["jwt-custom","prometheus","rate-limiting","syslog","file-log"],"available_on_server":{"correlation-id":true,"pre-function":true,"cors":true,"ldap-auth":true,"loggly":true,"hmac-auth":true,"zipkin":true,"request-size-limiting":true,"azure-functions":true,"request-transformer":true,"oauth2":true,"response-transformer":true,"ip-restriction":true,"statsd":true,"jwt":true,"proxy-cache":true,"basic-auth":true,"key-auth":true,"http-log":true,"ab-user":true,"jwt-custom":true,"datadog":true,"tcp-log":true,"rate-limiting":true,"post-function":true,"prometheus":true,"acl":true,"syslog":true,"file-log":true,"acme":true,"udp-log":true,"response-ratelimiting":true,"aws-lambda":true,"session":true,"bot-detection":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["bundled","jwt-custom","ab-user"],"admin_listen":["0.0.0.0:8001","0.0.0.0:8444 ssl"],"lua_ssl_verify_depth":1,"prefix":"\/usr\/local\/kong","nginx_conf":"\/usr\/local\/kong\/nginx.conf","cassandra_username":"kong","nginx_events_directives":[{"value":"auto","name":"worker_connections"},{"value":"on","name":"multi_accept"}],"admin_ssl_cert_key":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","dns_resolver":{},"nginx_upstream_keepalive_requests":"100","nginx_http_upstream_directives":[{"value":"100","name":"keepalive_requests"},{"value":"60s","name":"keepalive_timeout"},{"value":"60","name":"keepalive"}],"nginx_main_daemon":"on","stream_proxy_ssl_enabled":false,"nginx_acc_logs":"\/usr\/local\/kong\/logs\/access.log","pg_semaphore_timeout":60000,"proxy_listen":["0.0.0.0:8000 reuseport backlog=16384","0.0.0.0:8443 http2 ssl reuseport backlog=16384"],"client_ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","go_pluginserver_exe":"\/usr\/local\/bin\/go-pluginserver","dns_no_sync":false,"db_update_propagation":0,"stream_listen":["off"],"nginx_err_logs":"\/usr\/local\/kong\/logs\/error.log","cassandra_port":9042,"headers":["server_tokens","latency_tokens"],"nginx_http_client_max_body_size":"0","status_listen":["off"],"cassandra_lb_policy":"RequestRoundRobin","cluster_control_plane":"127.0.0.1:8005","nginx_http_ssl_prefer_server_ciphers":"off","pg_database":"kong","lua_package_cpath":"","admin_acc_logs":"\/usr\/local\/kong\/logs\/admin_access.log","cassandra_refresh_frequency":60,"nginx_pid":"\/usr\/local\/kong\/pids\/nginx.pid","nginx_main_worker_rlimit_nofile":"auto","admin_access_log":"logs\/admin_access.log","proxy_listeners":[{"listener":"0.0.0.0:8000 reuseport backlog=16384","proxy_protocol":false,"reuseport":true,"deferred":false,"ssl":false,"ip":"0.0.0.0","backlog=16384":true,"http2":false,"port":8000,"bind":false},{"listener":"0.0.0.0:8443 ssl http2 reuseport backlog=16384","proxy_protocol":false,"reuseport":true,"deferred":false,"ssl":true,"ip":"0.0.0.0","backlog=16384":true,"http2":true,"port":8443,"bind":false}],"db_cache_warmup_entities":["services","plugins"],"enabled_headers":{"latency_tokens":true,"X-Kong-Response-Latency":true,"Server":true,"X-Kong-Admin-Latency":true,"X-Kong-Upstream-Status":false,"Via":true,"X-Kong-Proxy-Latency":true,"server_tokens":true,"X-Kong-Upstream-Latency":true},"nginx_http_ssl_protocols":"TLSv1.2 TLSv1.3","db_cache_ttl":0,"nginx_events_multi_accept":"on","admin_ssl_cert_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","pg_ssl":false,"status_access_log":"off","cluster_listeners":[{"listener":"0.0.0.0:8005","proxy_protocol":false,"reuseport":false,"backlog=%d+":false,"deferred":false,"ssl":false,"ip":"0.0.0.0","port":8005,"http2":false,"bind":false}],"kong_env":"\/usr\/local\/kong\/.kong_env","cassandra_schema_consensus_timeout":60000,"log_level":"notice","admin_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/admin-kong-default.key","real_ip_recursive":"off","cassandra_repl_factor":1,"nginx_main_worker_processes":"auto","router_consistency":"strict","pg_port":5432,"cassandra_keyspace":"kong","ssl_cert_default":"\/usr\/local\/kong\/ssl\/kong-default.crt","nginx_http_ssl_session_timeout":"1d","error_default_type":"text\/plain","role":"traditional","client_ssl":false,"trusted_ips":{},"nginx_events_worker_connections":"auto","nginx_supstream_directives":{},"ssl_cert_key":"\/usr\/local\/kong\/ssl\/kong-default.key","pg_user":"kong","pg_password":"******","ssl_ciphers":"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384","nginx_admin_directives":{},"nginx_upstream_keepalive_timeout":"60s","nginx_http_directives":[{"value":"0","name":"client_max_body_size"},{"value":"off","name":"ssl_prefer_server_ciphers"},{"value":"8k","name":"client_body_buffer_size"},{"value":"TLSv1.2 TLSv1.3","name":"ssl_protocols"},{"value":"on","name":"ssl_session_tickets"},{"value":"1d","name":"ssl_session_timeout"},{"value":"prometheus_metrics 5m","name":"lua_shared_dict"}],"pg_host":"hawkeye-qa.cavqxjfmp25f.ap-south-1.rds.amazonaws.com","nginx_kong_stream_conf":"\/usr\/local\/kong\/nginx-kong-stream.conf","ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","go_plugins_dir":"\/usr\/local\/kong\/goplugins","db_update_frequency":5,"dns_order":["LAST","SRV","A","CNAME"],"dns_error_ttl":1,"nginx_optimizations":true,"nginx_http_upstream_keepalive_timeout":"60s","pg_timeout":60000,"nginx_http_upstream_keepalive_requests":"100","database":"postgres","nginx_upstream_keepalive":"60","nginx_worker_processes":"auto","nginx_http_status_directives":{},"lua_package_path":".\/?.lua;.\/?\/init.lua;","router_update_frequency":1,"upstream_keepalive":60,"pg_max_concurrent_queries":0,"proxy_ssl_enabled":true,"nginx_http_upstream_keepalive":"60","lua_socket_pool_size":30,"mem_cache_size":"128m","loaded_plugins":{"correlation-id":true,"pre-function":true,"cors":true,"ldap-auth":true,"loggly":true,"hmac-auth":true,"zipkin":true,"request-size-limiting":true,"azure-functions":true,"request-transformer":true,"oauth2":true,"response-transformer":true,"syslog":true,"statsd":true,"acme":true,"proxy-cache":true,"basic-auth":true,"key-auth":true,"http-log":true,"jwt":true,"bot-detection":true,"ab-user":true,"tcp-log":true,"session":true,"post-function":true,"datadog":true,"acl":true,"ip-restriction":true,"file-log":true,"jwt-custom":true,"udp-log":true,"response-ratelimiting":true,"aws-lambda":true,"rate-limiting":true,"prometheus":true,"request-termination":true},"db_resurrect_ttl":30,"cassandra_data_centers":["dc1:2","dc2:3"],"cassandra_consistency":"ONE","client_max_body_size":"0","admin_error_log":"logs\/error.log","pg_ssl_verify":false,"dns_not_found_ttl":30,"nginx_http_ssl_session_tickets":"on","dns_stale_ttl":4,"ssl_cipher_suite":"intermediate","cassandra_repl_strategy":"SimpleStrategy","status_error_log":"logs\/status_error.log","nginx_http_client_body_buffer_size":"8k","kic":false,"cluster_listen":["0.0.0.0:8005"],"nginx_kong_conf":"\/usr\/local\/kong\/nginx-kong.conf","real_ip_header":"X-Real-IP","dns_hostsfile":"\/etc\/hosts","admin_listeners":[{"listener":"0.0.0.0:8001","proxy_protocol":false,"reuseport":false,"backlog=%d+":false,"deferred":false,"ssl":false,"ip":"0.0.0.0","port":8001,"http2":false,"bind":false},{"listener":"0.0.0.0:8444 ssl","proxy_protocol":false,"reuseport":false,"backlog=%d+":false,"deferred":false,"ssl":true,"ip":"0.0.0.0","port":8444,"http2":false,"bind":false}],"ssl_cert_csr_default":"\/usr\/local\/kong\/ssl\/kong-default.csr","ssl_cert":"\/usr\/local\/kong\/ssl\/kong-default.crt","nginx_proxy_real_ip_recursive":"off","nginx_status_directives":{},"cassandra_ssl_verify":false,"cassandra_ssl":false,"admin_ssl_cert":"\/usr\/local\/kong\/ssl\/admin-kong-default.crt","proxy_error_log":"logs\/error.log","nginx_sproxy_directives":{},"nginx_proxy_directives":[{"value":"X-Real-IP","name":"real_ip_header"},{"value":"off","name":"real_ip_recursive"}],"nginx_daemon":"on","anonymous_reports":true,"cassandra_timeout":60000,"nginx_main_directives":[{"value":"on","name":"daemon"},{"value":"auto","name":"worker_rlimit_nofile"},{"value":"auto","name":"worker_processes"}],"status_listeners":{},"client_ssl_cert_key_default":"\/usr\/local\/kong\/ssl\/kong-default.key","client_body_buffer_size":"8k","cassandra_contact_points":["127.0.0.1"],"nginx_upstream_directives":[{"value":"100","name":"keepalive_requests"},{"value":"60s","name":"keepalive_timeout"},{"value":"60","name":"keepalive"}],"admin_ssl_enabled":true,"stream_listeners":{},"nginx_proxy_real_ip_header":"X-Real-IP","proxy_access_log":"logs\/access.log","nginx_stream_directives":[{"value":"stream_prometheus_metrics 5m","name":"lua_shared_dict"}]},"version":"2.0.4","node_id":"e6e5fc6d-c4ae-41aa-8218-639c5faad58e","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 3271":792341169209,"pid: 3270":199173721770,"pid: 3261":219124362351},"timers":{"pending":9,"running":2},"hostname":"ip-x.y.z"}`

**Comment by gszr** [comment]
Hi @jainrocks,

Thanks for posting this question!

Additionally to passing the `go_plugins_dir` directive (which simply tells the go-pluginserver where to find Go plugins), you need to enable the Go plugin - as with any custom Kong plugin. See [this](https://docs.konghq.com/2.0.x/configuration/#plugins).

So, do something like
```
go_plugins_dir = /usr/local/kong/goplugins
plugins = bundled,go-hello
```

**Comment by jainrocks** [comment]
Hi @gszr,
Thank you so much for the quick reply. I am getting this:

`
Kong stopped
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:64: 2020/06/10 15:03:09 stat /usr/local/kong/goplugins/go-hello.so: no such file or directory
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:455: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:455: in function 'get_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins/go.lua:481: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:151: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:427: in function 'init'
	init_by_lua:3: in main chunk
`
I am new to go language, please help.

**Comment by gszr** [comment]
@jackkav did you compile the Go plugin? Take a look at the makefile in this repo.

**Comment by jainrocks** [comment]
@gszr 
No I didn't compile earlier. My bad.
I tried compiling now using `make` 
I get:

go build -buildmode=plugin go-hello.go
make: go: Command not found
make: *** [go-hello.so] Error 127

**Comment by gszr** [comment]
From the error, it looks like you either don't have a Go compiler installed -- or it isn't in the `PATH`.

**Comment by jainrocks** [comment]
I didn't install or set any path for go in my Amazon linux instance, where kong is running.
Okay, will check for this.
Thanks a lot @gszr

**Comment by jainrocks** [comment]
@gszr 
Still getting the above issue.
After installing the go and setting the path.
`go env` is gibing the below result
`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ec2-user/.cache/go-build"
GOENV="/home/ec2-user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ec2-user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/usr/local/kong/goplugins/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build005273170=/tmp/go-build -gno-record-gcc-switches"
`
But still getting the above issue.

**Comment by gszr** [comment]
@jainrocks please post the entire output - in the same terminal you ran the `go env`.

**Comment by jainrocks** [comment]
@gszr 
Below is the output for the same.

<img width="1068" alt="Screenshot 2020-06-11 at 8 20 40 AM" src="https://user-images.githubusercontent.com/6883641/84339625-77c7b700-abbc-11ea-97bf-804a561b6791.png">

**Comment by jainrocks** [comment]
@gszr Please help here.

**Comment by gszr** [comment]
@jainrocks note that you are doing `sudo make`, while the commands before printed the environment for the current user, not `root`. Try `make`, without sudo.

**Comment by gszr** [comment]
Closing this as resolved. Please post an update if you still need help. Thanks!
