### ISSUE TITLE
package management?

### ISSUE THREAD

**Issue by karuppiah7890** [Kong/go-plugins#2]
Just running `make` doesn't work, as it need the `github.com/Kong/go-pdk` module - irrespective of the path of the repository.

May be we can have a package management system? I would recommend using golang modules, but that's available only after go 1.11 . Is that's okay, I would be willing to raise a PR with `go.mod` and `go.sum` 😄 

With go modules, people can place the repository anywhere and still make it work

**Comment by karuppiah7890** [comment]
With go modules, people can place the repository anywhere and still make it work

**Comment by gszr** [comment]
This has since been done. Thanks @karuppiah7890!
