### ISSUE TITLE
Kong is getting stop again and again

### ISSUE THREAD

**Issue by helal-abbas** [Kong/go-plugins#20]
kong     | 2022/08/19 13:43:56 [notice] 30#0: signal 17 (SIGCHLD) received from 91
kong     | 2022/08/19 13:43:56 [notice] 30#0: *14 [kong] go.lua:95 go-pluginserver terminated: exit 2, context: ngx.timer
kong     | 2022/08/19 13:43:56 [notice] 30#0: *14 [kong] go.lua:84 Starting go-pluginserver, context: ngx.timer

I'm facing this issue, kong is getting stop and stop again and again , how can I resolve this issue??

**Comment by gszr** [comment]
This issue has since been solved.
