### ISSUE TITLE
Can go plugin has daos/schema structure just like LUA plugin?

### ISSUE THREAD

**Issue by mong0520** [Kong/go-plugins#21]
I am trying to develop my plugins with GO, and wondering if go-plugins have ability to interactive with Kong's database/caches by using dao.lua / schema.lua just like what LUA does?
For example:
https://docs.konghq.com/gateway/latest/plugin-development/access-the-datastore/
https://github.com/Kong/kong/blob/master/kong/plugins/basic-auth/daos.lua
https://github.com/Kong/kong/blob/master/kong/plugins/basic-auth/schema.lua

**Comment by sm-tunglt** [comment]
as i understand, your go plugin run as a separated program
so you can do anything you want

**Comment by gszr** [comment]
You can connect to external databases, including Kong's, but the communication with the Kong process is limited to what the Go pdk exposes - https://pkg.go.dev/github.com/Kong/go-pdk. Example plugins can be seen at https://github.com/Kong/go-pdk/tree/master/examples
