### ISSUE TITLE
go-pluginserver error die loop 

### ISSUE THREAD

**Issue by hhofchina** [Kong/go-plugins#6]
error.log:
2020/04/09 20:42:49 [notice] 32346#0: signal 17 (SIGCHLD) received from 19941
2020/04/09 20:42:49 [notice] 32346#0: *13 [kong] go.lua:95 go-pluginserver terminated: exit 0, context: ngx.timer
centos 7

go-pluginserver  -version
Version: development
Runtime Version: go1.13.5

go-pluginserver -dump-plugin-info go-hello -plugins-directory $(pwd)
2020/04/09 20:47:47 failed to open plugin go-hello: plugin.Open("/root/go-plugins/go-hello"): plugin was built with a different version of package internal/cpu

**Comment by gszr** [comment]
Please check out https://github.com/Kong/go-pluginserver/issues/23.
